name: o
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'


#----------------------------------------------------------- dependencies
#-------------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  #----------  
  get: ^4.3.8
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  get_storage: ^2.0.3
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0+2

  #----------
  intl: ^0.17.0
  sqflite: ^2.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "images/appicon.jpeg"


#----------------------------------------------------------------- assets
#-------------------------------------------------------------------------

flutter:
  uses-material-design: true

  # assets:
  #   - images/person.jpeg
  #   - images/task.svg
  #   - images/


  fonts:
    - family: f1
      fonts:
        - asset: assets/fonts/Lato-Light.ttf

